buffers: {
  size_kb: 65536
  fill_policy: RING_BUFFER
}
duration_ms: 300000
write_into_file: true
file_write_period_ms: 1000
flush_period_ms: 1000
data_sources: {
  config {
    name: "linux.ftrace"
    target_buffer: 0
    ftrace_config {
      ftrace_events: "sched/sched_switch"
      ftrace_events: "sched/sched_waking"
      ftrace_events: "power/cpu_frequency"
      ftrace_events: "power/cpu_idle"
      ftrace_events: "sync/*"
      atrace_categories: "gfx"
      atrace_categories: "input"
      atrace_categories: "view"
      atrace_categories: "wm"
      atrace_categories: "sched"
      atrace_categories: "freq"
      atrace_categories: "idle"
      atrace_categories: "sync"
      atrace_categories: "ion"
      atrace_apps: "moe.swarm.hrrr"
      atrace_apps: "moe.swarm.eguitester.driver"
    }
  }
}
data_sources: {
  config {
    name: "linux.process_stats"
    target_buffer: 0
    process_stats_config {
      scan_all_processes_on_start: true
    }
  }
}
