name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  foundry:
    name: Foundry
    permissions:
      contents: write
    uses: aoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoa/eternalist-foundry/.github/workflows/pipeline.yml@7c5edcaf4c502b88acfd44e29be10d63d4615fe5
    with:
      publish: ${{ startsWith(github.ref, 'refs/tags/v') }}
